apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: flower }
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: 
          - celery
        args:
          - -A
          - app.celery_app.celery_app
          - flower
          - -l
          - DEBUG
        env:
        {{- range $key, $val := .Values.statefulset.env.values }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.statefulset.env.secrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ include "app.dbSecretsName" . }}
              key: {{ $val }}
        {{- end }}
