apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flower.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "flower.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}