apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "flower.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.global.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.env.port }}
      targetPort: {{ .Values.env.port }}