{{- range $alias, $secret := .Values.sharedSecrets }}
{{- if $secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default $alias $secret.name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{- range $key, $val := $secret.data }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
---
{{- end }}
{{- end }}

