apiVersion: v1
kind: Service
metadata:
  {{- $override := (include "app.backendServiceNameOrEmpty" .) -}}
  {{- if $override }}
  name: {{ $override }}
  {{- else }}
  name: {{ .Chart.Name }}-service
  {{- end }}
  namespace: foodgram
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  {{- with .Values.service.ports }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}