apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: foodgram
  labels:
{{ include "backend.labels" . | indent 4 }}
data:
  {{- with .Values.secret }}
  DJANGO_SETTINGS_MODULE: {{ .DJANGO_SETTINGS_MODULE | quote }}
  DB_HOST: {{ .DB_HOST | quote }}
  DB_PORT: {{ .DB_PORT | quote }}
  {{- end }}
