apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  namespace: foodgram
  labels:
{{ include "backend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.global.images.api }}
          image: {{ printf "%s:%s" .name .tag }}
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}
          command: {{ .Values.deployment.command | toJson }}
          args: {{ .Values.deployment.args | toJson }}
          ports:
            - containerPort: {{ .Values.service.ports.port }}

          volumeMounts:
            {{- with .Values.volumeMounts }}
            - name: {{ .media.name }}
              mountPath: {{ .media.mountPath }}
            - name: {{ .static.name }}
              mountPath: {{ .static.mountPath }}
            {{- end }}
          env:
            {{- range $key, $val := .Values.deployment.env.values }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range $alias, $mappmig := .Values.deployment.env.secrets }}
            {{- range $key, $val := $mappmig }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index $.Values.global.secrets $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
            {{- range $alias, $mappmig := .Values.deployment.env.config }}
            {{- range $key, $val := $mappmig }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ index $.Values.global.config $alias }}
                  key: {{ $val }}
            {{- end }}
            {{- end }}
      volumes:
        {{- with .Values.volumeMounts }}
        - name: {{ .media.name }}
          persistentVolumeClaim:
            claimName: {{ .media.claimName }}
        - name: {{ .static.name }}
          persistentVolumeClaim:
            claimName: {{ .static.claimName }}
        {{- end }}