auth:
  username: ref+vault://secrets/rabbitmq#/username
  password: ref+vault://secrets/rabbitmq#/password

service:
  type: LoadBalancer

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: rabbitmq.foodgram.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

persistence:
  enabled: true
  size: 8Gi

metrics:
  enabled: true