apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: foodgram
  labels:
{{ include "db.labels" . | indent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  clusterIP: None
  ports:
  {{- with  .ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }} 
  {{- end }}
  {{- end }}
  selector:
    app: {{ .Values.statefulset.app }}