apiVersion: v2
name: rabbitmq
description: A Helm chart for RabbitMQ

type: application

version: 0.1.0
appVersion: "3.13"

dependencies:
  - name: rabbitmq
    version: "16.0.14"
    repository: "https://charts.itis-3k-cloud.ru"

