apiVersion: v1
kind: Service
metadata:
  {{- $override := (include "app.nginxServiceNameOrEmpty" .) -}}
  {{- if $override }}
  name: {{ $override }}
  {{- else }}
  name: {{ .Chart.Name }}-service
  {{- end }}
  namespace: foodgram
  labels:
{{ include "nginx.labels" . | indent 4 }}
spec:
  {{- with .Values.service }}
  type: {{ .type }}
  ports:
    - port: {{ .ports.port }}
      targetPort: {{ .ports.port }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}