apiVersion: v1
kind: ConfigMap
metadata:
  namespace: foodgram
  name: {{ include "rabbitmq.configMapName" . }}
  labels:
{{ include "rabbitmq.labels" . | indent 4 }}
data:
  host: rabbitmq.rabbitmq.svc.cluster.local
  port: {{ .Values.service.port | quote }}
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val }}
  {{- end }}